// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDc_Jnso2iOu0jSdmzk5ID_CrF4nDdb8I',
    appId: '1:1033471969534:android:3b689d2b83417f493c3daf',
    messagingSenderId: '1033471969534',
    projectId: 'weighty-droplet-441008-k9',
    storageBucket: 'weighty-droplet-441008-k9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABfbMNKXNFRpLUl_W4gF0CxojJQrdp2BM',
    appId: '1:1033471969534:ios:e75aff21b641708b3c3daf',
    messagingSenderId: '1033471969534',
    projectId: 'weighty-droplet-441008-k9',
    storageBucket: 'weighty-droplet-441008-k9.firebasestorage.app',
    androidClientId: '1033471969534-i3dv50q4q1bcmo8e0unr7t6e5out2kha.apps.googleusercontent.com',
    iosClientId: '1033471969534-uhbgo496bg37e1ofjkaovngjeaodtgfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.vedioCall',
  );
}
